<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.modelDesign</groupId>
        <artifactId>mod-third-party</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>mod-third-party-biz</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-auth-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-system-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-third-party-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>mockwebserver</artifactId>
            <version>4.12.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
