/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyTodoRouteImport } from './routes/my-todo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as PersonalCenterIndexRouteImport } from './routes/personal-center/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AgileBoardIndexRouteImport } from './routes/agile-board/index'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as AiChatRouteImport } from './routes/ai.chat'
import { Route as SystemUserIndexRouteImport } from './routes/system/user/index'
import { Route as SystemTenantIndexRouteImport } from './routes/system/tenant/index'
import { Route as SystemRoleIndexRouteImport } from './routes/system/role/index'
import { Route as SystemPositionIndexRouteImport } from './routes/system/position/index'
import { Route as SystemMenuIndexRouteImport } from './routes/system/menu/index'
import { Route as SystemFileConfigIndexRouteImport } from './routes/system/file-config/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId.index'
import { Route as ProjectProjectIdTasksRouteImport } from './routes/project/$projectId.tasks'
import { Route as ProjectProjectIdTablesRouteImport } from './routes/project/$projectId.tables'
import { Route as ProjectProjectIdMembersRouteImport } from './routes/project/$projectId.members'
import { Route as SystemThirdPartyQyworkIndexRouteImport } from './routes/system/third-party/qywork/index'

const MyTodoRoute = MyTodoRouteImport.update({
  id: '/my-todo',
  path: '/my-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalCenterIndexRoute = PersonalCenterIndexRouteImport.update({
  id: '/personal-center/',
  path: '/personal-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgileBoardIndexRoute = AgileBoardIndexRouteImport.update({
  id: '/agile-board/',
  path: '/agile-board/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai/chat',
  path: '/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUserIndexRoute = SystemUserIndexRouteImport.update({
  id: '/system/user/',
  path: '/system/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemTenantIndexRoute = SystemTenantIndexRouteImport.update({
  id: '/system/tenant/',
  path: '/system/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoleIndexRoute = SystemRoleIndexRouteImport.update({
  id: '/system/role/',
  path: '/system/role/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemPositionIndexRoute = SystemPositionIndexRouteImport.update({
  id: '/system/position/',
  path: '/system/position/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemMenuIndexRoute = SystemMenuIndexRouteImport.update({
  id: '/system/menu/',
  path: '/system/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemFileConfigIndexRoute = SystemFileConfigIndexRouteImport.update({
  id: '/system/file-config/',
  path: '/system/file-config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdTasksRoute = ProjectProjectIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdTablesRoute = ProjectProjectIdTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const ProjectProjectIdMembersRoute = ProjectProjectIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ProjectProjectIdRoute,
} as any)
const SystemThirdPartyQyworkIndexRoute =
  SystemThirdPartyQyworkIndexRouteImport.update({
    id: '/system/third-party/qywork/',
    path: '/system/third-party/qywork/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-todo': typeof MyTodoRoute
  '/ai/chat': typeof AiChatRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/agile-board/': typeof AgileBoardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/personal-center/': typeof PersonalCenterIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/project/$projectId/members': typeof ProjectProjectIdMembersRoute
  '/project/$projectId/tables': typeof ProjectProjectIdTablesRoute
  '/project/$projectId/tasks': typeof ProjectProjectIdTasksRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/system/file-config/': typeof SystemFileConfigIndexRoute
  '/system/menu/': typeof SystemMenuIndexRoute
  '/system/position/': typeof SystemPositionIndexRoute
  '/system/role/': typeof SystemRoleIndexRoute
  '/system/tenant/': typeof SystemTenantIndexRoute
  '/system/user/': typeof SystemUserIndexRoute
  '/system/third-party/qywork/': typeof SystemThirdPartyQyworkIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-todo': typeof MyTodoRoute
  '/ai/chat': typeof AiChatRoute
  '/agile-board': typeof AgileBoardIndexRoute
  '/login': typeof LoginIndexRoute
  '/personal-center': typeof PersonalCenterIndexRoute
  '/project': typeof ProjectIndexRoute
  '/project/$projectId/members': typeof ProjectProjectIdMembersRoute
  '/project/$projectId/tables': typeof ProjectProjectIdTablesRoute
  '/project/$projectId/tasks': typeof ProjectProjectIdTasksRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/system/file-config': typeof SystemFileConfigIndexRoute
  '/system/menu': typeof SystemMenuIndexRoute
  '/system/position': typeof SystemPositionIndexRoute
  '/system/role': typeof SystemRoleIndexRoute
  '/system/tenant': typeof SystemTenantIndexRoute
  '/system/user': typeof SystemUserIndexRoute
  '/system/third-party/qywork': typeof SystemThirdPartyQyworkIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-todo': typeof MyTodoRoute
  '/ai/chat': typeof AiChatRoute
  '/project/$projectId': typeof ProjectProjectIdRouteWithChildren
  '/agile-board/': typeof AgileBoardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/personal-center/': typeof PersonalCenterIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/project/$projectId/members': typeof ProjectProjectIdMembersRoute
  '/project/$projectId/tables': typeof ProjectProjectIdTablesRoute
  '/project/$projectId/tasks': typeof ProjectProjectIdTasksRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/system/file-config/': typeof SystemFileConfigIndexRoute
  '/system/menu/': typeof SystemMenuIndexRoute
  '/system/position/': typeof SystemPositionIndexRoute
  '/system/role/': typeof SystemRoleIndexRoute
  '/system/tenant/': typeof SystemTenantIndexRoute
  '/system/user/': typeof SystemUserIndexRoute
  '/system/third-party/qywork/': typeof SystemThirdPartyQyworkIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-todo'
    | '/ai/chat'
    | '/project/$projectId'
    | '/agile-board/'
    | '/login/'
    | '/personal-center/'
    | '/project/'
    | '/project/$projectId/members'
    | '/project/$projectId/tables'
    | '/project/$projectId/tasks'
    | '/project/$projectId/'
    | '/system/file-config/'
    | '/system/menu/'
    | '/system/position/'
    | '/system/role/'
    | '/system/tenant/'
    | '/system/user/'
    | '/system/third-party/qywork/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-todo'
    | '/ai/chat'
    | '/agile-board'
    | '/login'
    | '/personal-center'
    | '/project'
    | '/project/$projectId/members'
    | '/project/$projectId/tables'
    | '/project/$projectId/tasks'
    | '/project/$projectId'
    | '/system/file-config'
    | '/system/menu'
    | '/system/position'
    | '/system/role'
    | '/system/tenant'
    | '/system/user'
    | '/system/third-party/qywork'
  id:
    | '__root__'
    | '/'
    | '/my-todo'
    | '/ai/chat'
    | '/project/$projectId'
    | '/agile-board/'
    | '/login/'
    | '/personal-center/'
    | '/project/'
    | '/project/$projectId/members'
    | '/project/$projectId/tables'
    | '/project/$projectId/tasks'
    | '/project/$projectId/'
    | '/system/file-config/'
    | '/system/menu/'
    | '/system/position/'
    | '/system/role/'
    | '/system/tenant/'
    | '/system/user/'
    | '/system/third-party/qywork/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyTodoRoute: typeof MyTodoRoute
  AiChatRoute: typeof AiChatRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRouteWithChildren
  AgileBoardIndexRoute: typeof AgileBoardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PersonalCenterIndexRoute: typeof PersonalCenterIndexRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  SystemFileConfigIndexRoute: typeof SystemFileConfigIndexRoute
  SystemMenuIndexRoute: typeof SystemMenuIndexRoute
  SystemPositionIndexRoute: typeof SystemPositionIndexRoute
  SystemRoleIndexRoute: typeof SystemRoleIndexRoute
  SystemTenantIndexRoute: typeof SystemTenantIndexRoute
  SystemUserIndexRoute: typeof SystemUserIndexRoute
  SystemThirdPartyQyworkIndexRoute: typeof SystemThirdPartyQyworkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-todo': {
      id: '/my-todo'
      path: '/my-todo'
      fullPath: '/my-todo'
      preLoaderRoute: typeof MyTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-center/': {
      id: '/personal-center/'
      path: '/personal-center'
      fullPath: '/personal-center/'
      preLoaderRoute: typeof PersonalCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agile-board/': {
      id: '/agile-board/'
      path: '/agile-board'
      fullPath: '/agile-board/'
      preLoaderRoute: typeof AgileBoardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/chat': {
      id: '/ai/chat'
      path: '/ai/chat'
      fullPath: '/ai/chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/user/': {
      id: '/system/user/'
      path: '/system/user'
      fullPath: '/system/user/'
      preLoaderRoute: typeof SystemUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/tenant/': {
      id: '/system/tenant/'
      path: '/system/tenant'
      fullPath: '/system/tenant/'
      preLoaderRoute: typeof SystemTenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/role/': {
      id: '/system/role/'
      path: '/system/role'
      fullPath: '/system/role/'
      preLoaderRoute: typeof SystemRoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/position/': {
      id: '/system/position/'
      path: '/system/position'
      fullPath: '/system/position/'
      preLoaderRoute: typeof SystemPositionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/menu/': {
      id: '/system/menu/'
      path: '/system/menu'
      fullPath: '/system/menu/'
      preLoaderRoute: typeof SystemMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/file-config/': {
      id: '/system/file-config/'
      path: '/system/file-config'
      fullPath: '/system/file-config/'
      preLoaderRoute: typeof SystemFileConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/tasks': {
      id: '/project/$projectId/tasks'
      path: '/tasks'
      fullPath: '/project/$projectId/tasks'
      preLoaderRoute: typeof ProjectProjectIdTasksRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/tables': {
      id: '/project/$projectId/tables'
      path: '/tables'
      fullPath: '/project/$projectId/tables'
      preLoaderRoute: typeof ProjectProjectIdTablesRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/project/$projectId/members': {
      id: '/project/$projectId/members'
      path: '/members'
      fullPath: '/project/$projectId/members'
      preLoaderRoute: typeof ProjectProjectIdMembersRouteImport
      parentRoute: typeof ProjectProjectIdRoute
    }
    '/system/third-party/qywork/': {
      id: '/system/third-party/qywork/'
      path: '/system/third-party/qywork'
      fullPath: '/system/third-party/qywork/'
      preLoaderRoute: typeof SystemThirdPartyQyworkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectProjectIdRouteChildren {
  ProjectProjectIdMembersRoute: typeof ProjectProjectIdMembersRoute
  ProjectProjectIdTablesRoute: typeof ProjectProjectIdTablesRoute
  ProjectProjectIdTasksRoute: typeof ProjectProjectIdTasksRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
}

const ProjectProjectIdRouteChildren: ProjectProjectIdRouteChildren = {
  ProjectProjectIdMembersRoute: ProjectProjectIdMembersRoute,
  ProjectProjectIdTablesRoute: ProjectProjectIdTablesRoute,
  ProjectProjectIdTasksRoute: ProjectProjectIdTasksRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
}

const ProjectProjectIdRouteWithChildren =
  ProjectProjectIdRoute._addFileChildren(ProjectProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyTodoRoute: MyTodoRoute,
  AiChatRoute: AiChatRoute,
  ProjectProjectIdRoute: ProjectProjectIdRouteWithChildren,
  AgileBoardIndexRoute: AgileBoardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PersonalCenterIndexRoute: PersonalCenterIndexRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  SystemFileConfigIndexRoute: SystemFileConfigIndexRoute,
  SystemMenuIndexRoute: SystemMenuIndexRoute,
  SystemPositionIndexRoute: SystemPositionIndexRoute,
  SystemRoleIndexRoute: SystemRoleIndexRoute,
  SystemTenantIndexRoute: SystemTenantIndexRoute,
  SystemUserIndexRoute: SystemUserIndexRoute,
  SystemThirdPartyQyworkIndexRoute: SystemThirdPartyQyworkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
