<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.modelDesign</groupId>
        <artifactId>server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>boot</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.casbin</groupId>
            <artifactId>casbin-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-asset-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-ai-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-auth-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-project-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-system-biz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-third-party-biz</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
