[request_definition]
r = sub, type, obj

[policy_definition]
p = sub, type, obj

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = g(r.sub, p.sub) && r.type == p.type && r.obj == p.obj
