<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.modelDesign</groupId>
        <artifactId>mod-system</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>mod-system-biz</artifactId>

    <dependencies>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>common</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-auth-api</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.modelDesign</groupId>
            <artifactId>mod-system-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.x-file-storage</groupId>
            <artifactId>x-file-storage-spring</artifactId>
            <version>2.3.0</version>
        </dependency>
    </dependencies>
</project>
